- filename: Aphogee_shampoing.jpg
  nom: "Shampoing hydratant protéiné Aphogee"
- filename: darcys-botanicals_petit.jpg
  nom: "Lait capillaire hydratant Darcys Botanicals"
- filename: Farity-karite-mangue-passion2.png
  nom: "Beurre capillaire au Karité parfum Mangue Passion"
- filename: Huile_de_carotte.jpg
  nom: "Huile de soin à la carotte"
- filename: Headband_bijoux.png
  nom: "Headband bijoux cheveux"
- filename: komoe_apres_shampoing.jpg
  nom: "Après shampoing Komoé"

 