- filename: Huile_de_carotte.jpg
  nom: "Huile de soin à la carotte"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: Aphogee_shampoing.jpg
  nom: "Shampoing hydratant protéiné Aphogee"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: komoe_apres_shampoing.jpg
  nom: "Après shampoing fortifiant Komoé"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename2: Farity-karite-mangue-passion2.png
  nom2: "Beurre de Karité Mangue Passion"
  description2: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename2: Headband_bijoux.png
  nom2: "Headband bijoux cheveux"
  description2: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename2: Farity-karite-mangue-passion2.png
  nom2: "Beurre de Karité Mangue Passion"
  description2: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename3: Headband_bijoux.png
  nom3: "Headband bijoux cheveux"
  description3: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"

  
