- filename: Huile_de_carotte.jpg
  nom: "Huile de soin à la carotte"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: Aphogee_shampoing.jpg
  nom: "Shampoing hydratant protéiné Aphogee"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: komoe_apres_shampoing.jpg
  nom: "Après shampoing Komoé"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: darcys-botanicals1.jpg
  nom: "Lait capillaire hydratant Darcys Botanicals"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: Farity-karite-mangue-passion2.png
  nom: "Beurre capillaire au Karité parfum Mangue Passion"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"
- filename: Headband_bijoux.png
  nom: "Headband bijoux cheveux"
  description: "kdhjfhiusfhc iudhfksdjhfklsgd mdfoidfs smofhhv dhdmg m"

